// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CreativeSeed struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Embedding pgvector.Vector
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type EvidenceLog struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Prompt       string
	SeedID       pgtype.UUID
	HumanScore   float64
	Reasoning    pgtype.Text
	EvidenceHash string
	PqcSignature string
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID                     pgtype.UUID
	Email                  string
	Password               string
	FirstName              string
	LastName               string
	FirebaseUid            string
	PqcPublicKey           string
	PqcPrivateKeyEncrypted string
	CreatedAt              pgtype.Timestamptz
}
