// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AuthorshipCertification struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	CollectionID      pgtype.UUID
	UserID            pgtype.UUID
	CertificationHash string
	PqcSignature      string
	AuditData         []byte
	CreatedAt         pgtype.Timestamptz
}

type Collection struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type CollectionItem struct {
	CollectionID pgtype.UUID
	ProjectID    pgtype.UUID
}

type CreativeSeed struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	Embedding pgvector.Vector
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type EvidenceLog struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Prompt       string
	SeedID       pgtype.UUID
	HumanScore   float64
	Reasoning    pgtype.Text
	EvidenceHash string
	PqcSignature string
	CreatedAt    pgtype.Timestamptz
}

type Project struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	SeedText        string
	Embedding       pgvector.Vector
	PlagiarismScore pgtype.Float8
	AiProbability   pgtype.Float8
	Status          string
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID                     pgtype.UUID
	Email                  string
	FirebaseUid            string
	PqcPublicKey           string
	PqcPrivateKeyEncrypted string
	CreatedAt              pgtype.Timestamptz
}
