// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createCreativeSeed = `-- name: CreateCreativeSeed :one
INSERT INTO creative_seeds (user_id, content, embedding, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, content, embedding, metadata, created_at
`

type CreateCreativeSeedParams struct {
	UserID    pgtype.UUID
	Content   string
	Embedding pgvector.Vector
	Metadata  []byte
}

func (q *Queries) CreateCreativeSeed(ctx context.Context, arg CreateCreativeSeedParams) (CreativeSeed, error) {
	row := q.db.QueryRow(ctx, createCreativeSeed,
		arg.UserID,
		arg.Content,
		arg.Embedding,
		arg.Metadata,
	)
	var i CreativeSeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createEvidenceLog = `-- name: CreateEvidenceLog :one
INSERT INTO evidence_logs (user_id, prompt, seed_id, human_score, reasoning, evidence_hash, pqc_signature)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, prompt, seed_id, human_score, reasoning, evidence_hash, pqc_signature, created_at
`

type CreateEvidenceLogParams struct {
	UserID       pgtype.UUID
	Prompt       string
	SeedID       pgtype.UUID
	HumanScore   float64
	Reasoning    pgtype.Text
	EvidenceHash string
	PqcSignature string
}

func (q *Queries) CreateEvidenceLog(ctx context.Context, arg CreateEvidenceLogParams) (EvidenceLog, error) {
	row := q.db.QueryRow(ctx, createEvidenceLog,
		arg.UserID,
		arg.Prompt,
		arg.SeedID,
		arg.HumanScore,
		arg.Reasoning,
		arg.EvidenceHash,
		arg.PqcSignature,
	)
	var i EvidenceLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prompt,
		&i.SeedID,
		&i.HumanScore,
		&i.Reasoning,
		&i.EvidenceHash,
		&i.PqcSignature,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, firebase_uid, pqc_public_key, pqc_private_key_encrypted)
VALUES ($1, $2, $3, $4)
RETURNING id, email, firebase_uid, pqc_public_key, pqc_private_key_encrypted, created_at
`

type CreateUserParams struct {
	Email                  string
	Password               string
	FirstName              string
	LastName               string
	FirebaseUid            string
	PqcPublicKey           string
	PqcPrivateKeyEncrypted string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.FirebaseUid,
		arg.PqcPublicKey,
		arg.PqcPrivateKeyEncrypted,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.FirebaseUid,
		&i.PqcPublicKey,
		&i.PqcPrivateKeyEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceLog = `-- name: GetEvidenceLog :one
SELECT id, user_id, prompt, seed_id, human_score, reasoning, evidence_hash, pqc_signature, created_at FROM evidence_logs WHERE id = $1
`

func (q *Queries) GetEvidenceLog(ctx context.Context, id pgtype.UUID) (EvidenceLog, error) {
	row := q.db.QueryRow(ctx, getEvidenceLog, id)
	var i EvidenceLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prompt,
		&i.SeedID,
		&i.HumanScore,
		&i.Reasoning,
		&i.EvidenceHash,
		&i.PqcSignature,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, email, firebase_uid, pqc_public_key, pqc_private_key_encrypted, created_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirebaseUid,
		&i.PqcPublicKey,
		&i.PqcPrivateKeyEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const searchCreativeSeeds = `-- name: SearchCreativeSeeds :many
SELECT id, user_id, content, embedding, metadata, created_at, 1 - (embedding <=> $2) AS similarity
FROM creative_seeds
WHERE user_id = $1
ORDER BY similarity DESC
LIMIT $3
`

type SearchCreativeSeedsParams struct {
	UserID    pgtype.UUID
	Embedding pgvector.Vector
	Limit     int32
}

type SearchCreativeSeedsRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Content    string
	Embedding  pgvector.Vector
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
	Similarity int32
}

func (q *Queries) SearchCreativeSeeds(ctx context.Context, arg SearchCreativeSeedsParams) ([]SearchCreativeSeedsRow, error) {
	rows, err := q.db.Query(ctx, searchCreativeSeeds, arg.UserID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCreativeSeedsRow
	for rows.Next() {
		var i SearchCreativeSeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
